version: '3.9'

services:
  db:
    image: postgis/postgis:latest
    container_name: fleeto-db
    environment:
      POSTGRES_DB: fleetdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: ../infra/Dockerfile.backend
    container_name: fleeto-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - POSTGRES_DB=fleetdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  frontend:
    build:
      context: ../frontend
      dockerfile: ../infra/Dockerfile.frontend
    container_name: fleeto-frontend
    command: npm run dev
    volumes:
      - ../fronten
